### ISSUE TITLE
Problem: Django 1.8 reaches EOL next April 1, 2018

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1016]
We need to move to Django 1.11 LTS.

It's easier and safer to upgrade version by version, i.e. start with 1.8 then 1.9 then 1.10 and finally 1.11.

**Comment by replaceafill** [comment]
Django has been upgraded to 1.11 in both repositories (AM and SS). A few additional changes have been made to ease the migration to 2.x addressing the `RemovedInDjango20Warning`s that I was able to identify through manual testing, `tox` and the AMAUATs.

One follow up task that I've identified is removing the `django-extensions` package. We're only using its `UUIDField` which has already been deprecated and removed in newer versions of the package because Django already provides a similar field. For reference see a similar change done in `a3m` https://github.com/artefactual-labs/a3m/commit/d8e46dae7ba3f4de6a06a5deb8c6874eefa15b8a

**Comment by sevein** [comment]
> One follow up task that I've identified is removing the django-extensions package. We're only using its UUIDField which has already been deprecated and removed in newer versions of the package because Django already provides a similar field. For reference see a similar change done in a3m artefactual-labs/a3m@d8e46da

Thanks, I've filed an issue to remind this to us! See https://github.com/archivematica/Issues/issues/1280.

**Comment by sromkey** [comment]
Closing as QA is working fine so clearly this upgrade is working!
