### ISSUE TITLE
Problem: Extract Packages is a mandatory stage for a Dataverse Transfer

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#1121]
The error here: https://github.com/artefactual/archivematica/issues/1120 is a result of `Extract Packages` not running. 

Consider what the best way to approach this is. I.e. do we want extract packages to be mandatory? Does the task call for a different extract packages? Do we want to work with the zip as well as? (i.e. provide the option?)

**Comment by ross-spencer** [comment]
Related, 'Extract Packages' may not be a desired configuration option for Dataverse transfers: https://github.com/artefactual/archivematica/issues/1149

**Comment by ross-spencer** [comment]
### Proposed Workflow

1. Convert Dataverse Structure determines if we are dealing with a bundle or not.
2. One of two unit variables are set if required:
   * `ExtractFromDataverse` if this is a bundle
   * `DoNotExtractFromDataverse` if this isn't a bundle
3. If ExtractFromDataverse then a VariableLinkPull diverts the Workflow to Extract Packages (Move to Extract Packages)
4. Packages are then extracted.
5. If `DoNotExtractFromDataverse` is set, then it doesn't matter if we have a workflow going via Extract Packages or not. `has_packages.py` will be updated to read the unit variable, and if it exists, it will exit with `no extractable packages`.

**Comment by joel-simpson** [comment]
I have tested the dev branch for AM [PR 1242](https://github.com/artefactual/archivematica/pull/1242) and SS [PR 398](https://github.com/artefactual/archivematica-storage-service/pull/398) and can confirm this issue is now fixed. 
The SS PR means that any 'bundles' (for tabular data) are being extracted by the storage service. Remaining ZIP files are left and users can choose to set 'extract packages' as they need. 
This will need final QA once the PRs are merged, but for now it is looking good.
