### ISSUE TITLE
Enhancement: make indexless more configurable

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#1172]
Users may want to use Archivematica in indexless mode, but may still want to access transfer backlog (through the Backlog and Appraisal tabs) or archival storage (through the archival storage tab). This would give some increased performance that is associated with running Archivematica in indexless mode but allows me more flexibility for running different digital preservation workflows.

**Comment by sromkey** [comment]
Specifically:
Disabling the search index currently disables three tabs (Backlog, Appraisal and Archival Storage).
The proposal is to be able to disable only those related to the transfers index (Backlog, Appraisal, and the associated micro-services) or only those related to the AIP index (Archival Storage and associated micro-services).

**Comment by jraddaoui** [comment]
Hi @jhsimpson,

First I was thinking to change the current `SEARCH_ENABLED` environment/config variable to accept a list of "indexes" (e.g.: `SEARCH_ENABLED=transfers, aips`), but later I've realized that we could maintain that variable, to avoid changes in the instances using it, and add a couple of variables more (all default to `true`):

- `SEARCH_ENABLED`: takes precedence over the next two if set to `false`.
- `SEARCH_TRANSFERS_ENABLED`: if `SEARCH_ENABLED=true`, enable/disable Transfer related index(es).
- `SEARCH_AIPS_ENABLED`: if `SEARCH_ENABLED=true`, enable/disable AIP related index(es).

This is just to maintain the current var., otherwise we could just use the last two.

Thoughts?

**Comment by jraddaoui** [comment]
Also, we could have this ready before the 1.8 code freeze by the end of this month if we take a decision soon enough. **At least we should think about including #1174 in 1.8 if not this one.**

**Comment by sevein** [comment]
Can't we extend the purpose of SEARCH_ENABLED while maintaining backward compatibility? That would be my choice only because I think we're adding too many settings which is inconvenient for the user particularly because in some cases like in this one you have to define them across more than one service.

A possible approach...

```
def _search_enabled(value):
    known_indices = ("transfers", "aips",)
    boolean = _fancy_booleaner(value) #  e.g. value in ("yes", "y", "True", "true", "1",)
    if boolean is not None:
        return boolean
    else
        return set([item for item in var.split(",") if item in known_indices])

SEARCH_ENABLED = _search_enabled(config.get('search_enabled'))
```

**Comment by jraddaoui** [comment]
I like that idea, thanks @sevein!

If it's a boolean, we could check its value inside the function to return an empty list when it's false or a list with all the known indices when it's true, to ease the checks over the setting value later on.

**Comment by sevein** [comment]
Good idea, thanks.

**Comment by sevein** [comment]
Definitely better if the function is expected to return only one type.

**Comment by jraddaoui** [comment]
This work has been merged in qa/1.x. I'm not sure what will be the best way to test it as it will require testing different pipeline configurations. The values that should be tested for the `search_enabled` config attribute are:

- `transfers`: Only transfers index.
- `aips`: Only AIPs index.
- `aips,transfers` (the same as `true`): Both indexes.
- `false`: Indexless mode.

This value has to be set on the three components in a consistent manner for each case.

**Comment by peterVG** [comment]
Tested successfully on Xenial where `search_enabled` config attribute was set to 

- `transfers`: search only enabled for Backlog and Appraisal tabs (no Archival Storage tab)
- `aips`: search only enabled for Archival Storage (no Backlog or Appraisal tabs)
- `aips, transfers` or `true`: search enabled for both indexes (all Dashboard tabs showing)
- `false`: no indexes enabled (no Backlog, Appraisal, or Archival Storage tab showing)

**Comment by sallain** [comment]
@peterVG did this change get documented?

**Comment by sallain** [comment]
Documented and added to release notes.
