### ISSUE TITLE
Problem: index_aip crashes elasticsearch for large transfers

### ISSUE THREAD

**Issue by payten** [artefactual/archivematica#1199]
While testing large and multiple transfers for the rate limiting investigation, we noticed elasticsearch crash when it hit max-memory.  Transfers with many files produced larger JSON documents (50 to 100MB), and the post to elasticsearch would take longer than the 10 second timeout causing a retry soon after.  As these retries pile up, elasticsearch quickly hits its memory limit and barfs.

We tried increasing the elasticsearch memory allocation to 3x the default and still hit the limit.  However, we think we can avoid this situation by increasing the default timeout from 10 seconds to 5 minutes during AIP indexing.  This will lesson the load the elasticsearch server (by avoiding all those retries) and allow time for those large documents to be indexed.

We'll test this out and prepare a PR.

**Comment by ross-spencer** [comment]
Related (I think) https://github.com/artefactual/archivematica/issues/1136

**Comment by payten** [comment]
Thanks @ross-spencer!  We've spoken to @jhsimpson and he's given us an overview of the greater problem.  We'll investigate reducing the size of this index_aip payload (yet still retain the fields required for searching) and report back.

**Comment by ross-spencer** [comment]
Thanks @payten - is there a link to that greater exposition already on GitHub or the AM Wiki for the community to benefit from? cc. @jhsimpson

**Comment by marktriggs** [comment]
Hi all,

I'm not sure if it's written down anywhere, but @jhsimpson mentioned that some users have seen very large Elasticsearch documents produced when indexing transfers containing lots of files--in the area of 1GB in some cases.

The bulk of this size seems to be due to the `mets` field that gets indexed as a part of the AIP, as this field contains a JSON representation of the full METS document.  I wanted to add a note here because it looks to me that this field isn't actually used for searching, and could potentially be dropped altogether.

The place it *does* show up in the Dashboard is when you search for an AIP and click "View raw".  You'll see a document like this:

```
{
  "_id": "AWSgvw03Sq8t1C0dM5NB", 
  "_index": "aips", 
  "_source": {
    "AICID": null, 
    "countAIPsinAIC": null, 
    "created": 1531705205, 
    "encrypted": false, 
    "filePath": "/var/archivematica/sharedDirectory/www/AIPsStore/0241/211c/ed41/4bff/837b/8400/c589/06aa/test_1-0241211c-ed41-4bff-837b-8400c58906aa.7z", 
    "identifiers": [], 
    "isPartOf": null, 
    "mets": {
      "ns0:mets_dict_list": [
        {
          "@xmlns:ns0": "http://www.loc.gov/METS/", 
          "@xmlns:ns2": "http://www.loc.gov/premis/v3", 
          "@xmlns:ns3": "info:lc/xmlns/premis-v2", 
          "@xmlns:ns4": "http://www.w3.org/1999/xlink", 
          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", 
          "@xsi:schemaLocation": "http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version111/mets.xsd", 
          "ns0:amdSec_dict_list": [
  ...
```

So you get a dump of the raw Elasticsearch document, which happens to contain the `mets` field.  It's not immediately clear whether anyone would be depending on having this there.  Looking at https://projects.artefactual.com/issues/4953, it seems that this is the reason that the field was added in the first place.

Otherwise, the contents of the `mets` field don't seem to be searchable anywhere that I can see.  Searches generally seem to happen at the level of `aipfile` documents, not the `aip` documents.  As an experiment, I modified the AIP indexing to include a unique token in the `mets` field and I was unable to do a search through the Dashboard that hit that unique token.

If that's all correct, I guess the question is whether the "View raw" functionality for AIPs is useful enough to warrant keeping the `mets` field around.  It seems like indexing would be more robust if that field were dropped.

**Comment by jhsimpson** [comment]
Thanks @marktriggs and @payten for looking into this.  My understanding of this issue so far:

1) there is a json document being created, one for each aip, that is sent to the 'aip' index in elasticsearch, that includes a large field called 'mets'.  That mets field is not being indexed and nothing from that field can be searched for in the current archival storage tab of the dashboard, or via any api. The only place where the mets field of this json document is visible is via the 'view raw' link that appears beside each aip in search results in the archival storage tab.
2) For each aip many json documents are created, one for each file in the aip, that are sent to the 'aipfile index in Elasticsearch.  These all contain a mets field, with metadata about one specific file (a copy of the same metadata is in the mets field of the aip json document). The aipfile index is indexing this mets field but it is not indexing the entire mets field, only some parts of it.
3) there are 'view raw' links in the archival storage tab search results at both the aip level and the file level.

**Possible Solutions**
a) change the aip indexes json so it does not include a mets section.  This has two impacts - reducing  the size of the json that is visible in the 'view raw ' link of an aip, and reducing the size of the json document that is sent to elasticsearch.  The size reduction is substantial.  In a test @marktriggs mentioned offline, a 25mb json document was reduced to 450 bytes by simplying removing the mets field.  This one change would likely address the bulk of the original problem described in this issue by dramatically reducing the chance of elasticsearch crashing.  It is still possible that changes to the default timeout and number of retries should be applied, as described by @payten in the issue description.
b) remove the 'view raw' links (ether all of them, or just from the aip level).  This would mask the one impact from solution a) and i don't think there is really any value to most end-users in keeping these links.  However, this doesn't directly address the original issue and there is probably no harm in leaving the links there.
c) the aipfile level json could also be modified to contain fewer fields inside the mets field, just the ones that are actually being indexed. That is slightly higher hanging fruit, and would require some analysis to determine exactly what modifications to make.

**Comment by ross-spencer** [comment]
If it is relevant, and if I read this correctly, I was looking at the METS field as a solution for duplicate detection across AIPS: https://gist.github.com/ross-spencer/895b5a346729075dd98f76cd5314728c. There's a bit of unexplored potential in the ES index for more than we expose currently. 

Maybe one of the devs here can confirm whether my script would be impacted? 

Also, are we in the process of updating ES? Would the update alone ease some of the issues we're seeing here?

**Comment by jhsimpson** [comment]
@ross-spencer the upgrade es issue is https://github.com/artefactual/archivematica/issues/1172 .  There are two related issues (1171 and 1173). Upgrading elasticsearch won't have any impact on this issue, I don't think.  The json document being indexed will still be large and exceed memory and timeout default settings.   

The script you linked to would be broken by solution a) as I described it (removing the mets field from the aip document type in the aips index).  However, I think for the purposes of detecting duplicates, it would be better to use the storage service as the system of recordt o, rather than the ES index, for a couple reasons:
- the ES index only has content on files that were produced by a single pipeline - there may be aips listed in the storage service that were produced by other archivematica instances (old retired pipelines, or other existing parallel pipelines) that are missing from any given ES index
- the ES index could be missing data - it is possible to configure Archivematica (from 1.7 on) to disable indexing, and as this issue highlights, sometimes indexing crashes.  All files should be listed in the storage service however.

In order to use the storage service for that problem it may be necessary to update or change the Storage Service rest api, but the data should exist in the storage service database.

**Comment by ross-spencer** [comment]
Thanks @jhsimpson. When there's an opportunity I'd like to take the time to confirm the data in in the Storage Service, especially as a potential way to satisfy user reporting requirements. I take your point as well about the potential to look across alternative pipelines too. That would definitely be more useful over time.

**Comment by sevein** [comment]
FYI I've closed #274 (old pull request related to this same problem) but the associated branch has not been removedas itt could be used for future reference.

**Comment by jraddaoui** [comment]
Moving this back to in progress as we identified a minor issue in the ES mappings that would be nice to address before the release.

**Comment by jraddaoui** [comment]
Please notice, after this enhancements a big part of the `aips` and `aipfiles` indexes mappings will change. For example, we recently analyzed the viability of using Kibana to generate reports based on the file formats, with this enhancements the location of that value will be different:

- **<= 1.10**: `METS.amdSec.ns0:amdSec_dict_list.ns0:techMD_dict_list.mets:mdWrap_dict_list.ns0:xmlData_dict_list.ns1:object_dict_list.ns1:objectCharacteristics_dict_list.ns1:format_dict_list.ns1:formatDesignation_dict_list.ns1:formatName.keyword`
- **>= 1.11**: `METS.amdSec.mets:amdSec_dict_list.mets:techMD_dict_list.mets:mdWrap_dict_list.mets:xmlData_dict_list.premis:object_dict_list.premis:objectCharacteristics_dict_list.premis:format_dict_list.premis:formatDesignation_dict_list.premis:formatName.keyword`

Nevertheless, the improvement using `lxml.etree` (which causes the mapping changes) is quite noticeable and we don't target those fields directly (at least internally). Because we have dynamic mappings at the moment, there won't be a problem indexing new documents in existing indexes but there is not going to be consistency between <= 1.10 and >= 1.11 documents.

However, if we ever develop something that depends on those fields we should extract the needed information from the dynamic fields to fixed ones and, in that process, we could consider both nomenclatures in the migration path that will be needed. For those reasons, we're considering to not include a way to update existing indexes on this release but, please, let us know if you think otherwise.

**Comment by jraddaoui** [comment]
Another reason that I forgot to mention is that a full re-index of existing AIPs would avoid the issue, but that's something that is not always possible.

**Comment by ross-spencer** [comment]
I was asked to comment on this, primarily as another person internally who has explored using the ES index for more complex reporting previously.

I misunderstood the direction initially. If I understand it now, then having looked a little deeper at 1.10 and the proposal for 1.11 and the fix in 1571, then the original PR (1463?) is a little more "dramatic", but not that much i.e. we lose the ability to quickly query something like the METS structMap (as it's no longer indexed), but as Radda notes we haven't any features based on this. We also maintain a lot of information too. So for example, for reporting on file format breakdown in Archivematica, and making sure that breakdown is accurate for making preservation decisions (for example, removing duplicates, and identifying format tool), then we still have important PREMIS information we can access also as Radda notes. 

In 1571 we will just removing the namespace declaration to complete the work here, and this makes it a little clearer to write a query for. Another approach folks have used is `jq` which may also be a little easier to use now too, the JSON is cleaner.

**Comment by jraddaoui** [comment]
Thanks @ross-spencer. Ready for review again.

**Comment by ross-spencer** [comment]
Okay, first attempt at proving the efficacy of this fix, we created 30000 `tzx` skeleton files. Those files will generate a little metadata, e.g. format identification, and of course, virus scanning, and checksum generation. Probably not much else without FITS on. 

This resulted in a `6,720,374` line file. `407.6MB.`.

And it `727 seconds` or `12.11 minutes`. 

![image](https://user-images.githubusercontent.com/1880412/77462011-d5c4d980-6dd9-11ea-8438-150fe0a845c6.png)

Which isn't forever. Will need to confirm if we need a 1.10 comparison.

**Comment by ross-spencer** [comment]
Thumbs up from the team! No need to go back in time on this one :+1: 

![](https://media3.giphy.com/media/3Ja3CqSi1MD6w/giphy.gif?cid=790b7611c5db1cd28a910673eb35bbe357131add48b15846&rid=giphy.gif)

If anyone wants to, those files are, [17MB ZIP]: [tzx.zip](https://github.com/artefactual/archivematica/files/4377017/tzx.zip)
