### ISSUE TITLE
Upgrade on redhat 7 issue

### ISSUE THREAD

**Issue by jlong2git** [artefactual/archivematica#1651]
I upgraded to 1.12 from 1.10  on redhat 7 and followed the directions 
https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#upgrade

I got some Django errors during the yum update so I upgraded to Django 1.11.29
and did a yum reinstall and seemed to work
but I get a bunch of 404s on the dashboard because of the hash that is inserted on the media filenames
I did not have this issue with previous upgrades
Not sure how to fix this other than edit the source code 

examples
jquery-ui.9f933abedadb.css
bootstrap.e7aa4e830a64.css
font-awesome.min.bf0c425cdb73.css
etc...

**Comment by ross-spencer** [comment]
Hi Jason - thanks for logging this. Are you still noticing this as an issue a few weeks in? Are you able to repost on https://github.com/archivematica/Issues/issues using the form there? This issues repository is largely here because of the legacy tickets and we collect all current Archivematica and related issues over on the other one now. (We'll close this issue here once it is moved).

**Comment by sevein** [comment]
Acknowledging Ross' words, I'd like ot add that I believe this is an equivalent: https://github.com/archivematica/Issues/issues/1312 - so I will close this. Also, I believe that [Release v1.12.1](https://wiki.archivematica.org/Archivematica_1.12.1_and_Storage_Service_0.17.1_release_notes) addressed the problem.
