### ISSUE TITLE
Problem: this repo uses git submodules

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#585]
We have other ways to manage dependencies, e.g. pip in Python, bower in frontend, etc... git submodules will do it but they also introduce unnecessary complexity in the development workflow. The less solutions we combine the better.

This is the current situation:

- archivematica-fpr-admin is still a git submodule but it's moving to pip here: https://github.com/artefactual/archivematica/pull/506/commits - soon to be merged!
- appraisal-tab used to be a git submodule but it's been vendored since ee43ae42ff3b10d3fc9f0e0989316adcce7e48b1. We could also use bower, etc...

base64 is the only one left! It's also a frontend asset manageable from bower, checking in bower_modules/ in the repo if you wish to avoid extra steps during deployment. The submodule was introduced here: 4d07f82f30921bfc88659cc2259f444c76c4ec31. For some reason the symlink is not a symlink anymore, see https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/media/js/vendor/base64.js.

My suggestion is to vendor base64 or introduce bower_modules/.
Wait until #506 is merged!

**Comment by sevein** [comment]
Fixed in #619.

**Comment by jhsimpson** [comment]
This issue is resolved, correct?  It can be closed.  Please re-open if I am wrong.

**Comment by kellyannewithane** [comment]
@jrwdunham Can you make suggestions for documentation updates?

**Comment by jrwdunham** [comment]
@kellyannewithane I don't think this should have any bearing on the user-facing and administrator-facing documentation. 

However, it makes some of the developer-facing documentation out-of-date. The page at https://wiki.archivematica.org/Dashboard talks about the external/ and fpr/ directories under archivematica/src/dashboard/src/ but those directories no longer exist because of this recent submodule removal stuff.  That, is the bullets with the following text can probably just be removed:

* external: External dependencies, often git submodules.
* fpr: Views related to the Preservation Planning tab. This in the FPR-admin submodule from externals, and contains all FPR modification views.

Similarly, this bullet can be removed from https://wiki.archivematica.org/Getting_started:

* Format Policy Registry: Submodule shared between Archivematica and the Format Policy Registry (FPR) server that displays and updates FPR rules and commands

Also on the Getting_started page, the `archivematica_src_install_appraisaltab` variable referenced there is no longer relevant in the ansible scripts for AM 1.7.

I will add more to this comment later.

**Comment by sevein** [comment]
But some of that stuff is still relevant in AM 1.6 or stable/1.6.x, isn't it?

**Comment by sromkey** [comment]
@jrwdunham I'm moving this into Documentation column if you could take a look at it and confirm the docs are up to date.

**Comment by jrwdunham** [comment]
@sevein @sromkey I've made changes reflecting this on the https://wiki.archivematica.org/Dashboard#Sections page: see the boldface text in the `externals` and `fpr` bullets.

I did not remove `# archivematica_src_install_appraisaltab: "yes"`  from https://wiki.archivematica.org/Getting_started because that Ansible var is only removed in the role as of qa/1.7.x and it's commented out in the wiki code block anyways.

Also, it no longer made sense to me to remove the "Format Policy Registry" bullet from https://wiki.archivematica.org/Getting_started.

Please let me know if you think changes should be made or if we can now move this out of Documentation and into Done.
