### ISSUE TITLE
MCPClient: exit gracefully if clamd fails to scan (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica#668]
Merge https://github.com/JiscRDSS/archivematica/pull/17/commits/c62a1c1dacb2b24f5368550bec2a8097724381a9 into core.

This provides nicer handling of clamd failures.

**Comment by lower29** [comment]
The commit https://github.com/JiscRDSS/archivematica/commit/c62a1c1dacb2b24f5368550bec2a8097724381a9 does not stand alone in the JiscRDSS repo, it builds on other changes. I just tried to do a simple cherry-pick into a dev branch based on `qa/1.x` and it failed the merge.

Looking through the history, @sevein made significant changes to `archivematicaClamscan.py` in https://github.com/JiscRDSS/archivematica/commit/51cd3f9d58cb52813a99eadb5bd0d695ad78e949 - he moved code into functions instead of everything being under `if __name__ == '__main__'`. I can't find a PR or issue for it, just the commit.

I'm going to look at merging in both commits, in the hope that that'll resolve the merge conflict. I'm aware however I'm working out of my depth a little here, so someone more familiar with Archivematica will need to review carefully to confirm that this change is the correct thing to do.

**Comment by lower29** [comment]
Merging the cherry-pick for https://github.com/JiscRDSS/archivematica/commit/51cd3f9d58cb52813a99eadb5bd0d695ad78e949 also failed: it makes a change that relies on the `CONFIG_MAPPING` change introduced in https://github.com/JiscRDSS/archivematica/pull/3/commits/045619e6b307219614e0185c0b189c8dc5c5c8f9 (and part of https://github.com/JiscRDSS/archivematica/pull/3/).

There's also a change to the `MCPClient.Dockerfile` too, which also isn't part of the artefactual fork yet.

So this isn't a simple one-commit merge: it has dependencies on the configuration work needed for #664.

**Comment by sevein** [comment]
@lower29 you were totally right! I'm going to close this issue because I've done this as part of #663 (PR #682). Thank you both!

**Comment by sevein** [comment]
a36a9bf
