### ISSUE TITLE
Problem: antivirus scanning errors if file is too big

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#753]
Some defaults in [clamd.conf](https://linux.die.net/man/5/clamd.conf) are causing the antivirus scanning client script to fail. I believe these are the attributes involved:

```
■ MaxScanSize SIZE
Sets the maximum amount of data to be scanned for each input file. Archives and other containers are recursively extracted and scanned up to this value. Warning: disabling this limit or setting it too high may result in severe damage to the system.
Default: 100M

■ MaxFileSize SIZE
Files larger than this limit won't be scanned. Affects the input file itself as well as files contained inside it (when the input file is an archive, a document or some other kind of container). Warning: disabling this limit or setting it too high may result in severe damage to the system.
Default: 25M

■ StreamMaxLength SIZE
Clamd uses FTP-like protocol to receive data from remote clients. If you are using clamav-milter to balance load between remote clamd daemons on firewall servers you may need to tune the Stream* options. This option allows you to specify the upper limit for data size that will be transfered to remote daemon when scanning a single file. It should match your MTA's limit for a maximum attachment size.
Default: 10M
```

I tried to change their values to:
```
StreamMaxLength 0
MaxScanSize 0
MaxFileSize 0
```

Zero means unlimited. However the value of `StreamMaxLength` seems to be hard-coded to 4G (read [this](http://lists.clamav.net/pipermail/clamav-win32/2012-May/000807.html)).

With the previous config, I've made the following tests:

![image](https://user-images.githubusercontent.com/606459/31469447-623b2cee-ae96-11e7-8b6f-4d6a5f28b366.png)

The largest one (4.1G) failed.

The output of the client script is:

```
archivematicaClamscan.py: ERROR     2017-10-11 22:05:26,861  archivematica.mcp.client.clamscan:main:95:  Unexpected error scanning: /var/archivematica/sharedDirectory/currentlyProcessing/Test-4.1G-File-With-Accents_2-31a95a67-a0e0-4546-815d-fdbeebd41da6/objects/Volcán.jpg
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaClamscan.py", line 93, in main
    result = client.instream(open(target))
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/clamd/__init__.py", line 190, in instream
    self.clamd_socket.send(size + chunk)
error: [Errno 104] Connection reset by peer
archivematicaClamscan.py: INFO      2017-10-11 22:05:26,867  archivematica.mcp.client.clamscan:record_event:56:  Recording event for fileUUID=29ffd407-35c6-41bf-ae5a-30dee0589962 outcome=Fail
```

In /var/log/clamav/clamav.log:

```
WARNING: INSTREAM: Size limit reached, (requested: 1024, max: 1023)
```

**Comment by sevein** [comment]
AFAIK, AM 1.6 also did stream the contents (used `INSTREAM`). 
Compare the [old version](https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/MCPClient/lib/clientScripts/archivematicaClamscan.py) with the [new version](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/archivematicaClamscan.py) of `archivematicaClamscan.py`.

Why `clamdscan` was able to stream files larger than 4G (@hakamine has tested with large files before) but https://pypi.python.org/pypi/clamd doesn't?

**Comment by hakamine** [comment]
Just tried with a 1.6.x archivematica instance. It looks like clamdscan is not scanning large files and just returning a pass (note the scanning time is 0):

```
artefactual@amdemo2:~/archivematica-sampledata$ tree -s Accents-4.1G/
Accents-4.1G/
└── [ 4299161600]  Volcán

0 directories, 1 file
artefactual@amdemo2:~/archivematica-sampledata$ clamdscan - < Accents-4.1G/Volcán
fd[10]: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 0.001 sec (0 m 0 s)
artefactual@amdemo2:~/archivematica-sampledata$ echo $?
0
```
AM log:
```
Command: archivematicaClamscan_v0.0 "367da03b-fa6f-485d-bfad-186546b5a823" "/var/archivematica/sharedDirectory/currentlyProcessing/Accents-4.1G-1d51fd4f-315b-460d-8cbd-2efacfdf360b/objects/Volcán" "%date%" "%taskUUID%"
STDOUT

Clamscan command: clamdscan - < /var/archivematica/sharedDirectory/currentlyProcessing/Accents-4.1G-1d51fd4f-315b-460d-8cbd-2efacfdf360b/objects/Volcán
Clamscan version command: clamdscan -V
Event outcome: Pass
```
The result is the same even if the clamdscan parameters (StreamMaxLength, MaxScanSize, MaxFileSize) are set to 0 in clamd.conf (and restarting the service).

For other smaller files, scanner is running:
```
artefactual@amdemo2:~/archivematica-sampledata$ clamdscan - < SampleTransfers/ISODiskImage/images.iso
fd[10]: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 2.550 sec (0 m 2 s)
```

**Comment by lwo** [comment]
We encounter the same issue with qa/1.7 . As a workaround we upped StreamMaxLength to 2GB with which we could continue testing. But surely in production there always will be that larger file

**Comment by sevein** [comment]
@lwo thanks for sharing that.

I've been playing with clamdscan and these are the things I've observed:

- `clamdscan --stream FILE` which streams the file using `INSTREAM` is definitely limited to 4G. You even get a warning when `StreamMaxLength` is too high,, e.g. `WARNING: Numerical value for option StreamMaxLength too high, resetting to 4G`.

- `clamdscan FILE` tells clamd to read the file using `SCAN` instead of stream it. As observed, I can scan a file of 1G but it didn't scan a 2.5G file. I'm not sure where's the limit but somewhere in between!

- `clamdscan - < FILE` doesn't really make a difference. It just loads from STDIN but it doesn't have an impact on whether the file is streamed or referenced.

---

What I'd suggest to close this issue is to have the client script check the size of the file and decide between one of the following options:
- When `size < 1G`: file is streamed/referenced to clamd.
- When `size >= 1G`: file is scanned using `clamscan`.

`clamscan` is the alternative CLI scanner that doesn't make use of the `clamd` daemon. The problem with that is that the virus signatures need to be loaded each time it's executed.

- **client/server model (streaming)**:
  `clamdscan --stream file10M` took: `0.321 sec`, `0.335 sec` and `0.470 sec`(UNIX socket)

- **client/server model (reference)**:
  `clamdscan file10M` took: `0.053 sec`, `0.035 sec`, `0.044 sec` (UNIX socket)

- **regular cli (loading signatures on demand)**:
   `clamdcan file10M` took: `21.133 sec`, `20.351 sec` and `20.100sec`

From the results we can guess that reading the signatures take about 20 seconds. I think that's the price users will have to pay when dealing with larger files.

Thoughts?

**Comment by lwo** [comment]
But assuming that avclam introduced the limit to prevent it from using up all memory and falling back on swap... then files whose size is close to the available system resources will slow down the process and at worse the scan will still fail.

Maybe it is better to copy the avclam behaviour are give a Pass rather than to fallback on clamscan.

**Comment by sevein** [comment]
Unless you really want to scan very big files. But we could add options so it's up to the user.

**Comment by sevein** [comment]
I've just been reported another error in qa/1.7.x. Nothing new, basically clamad closing the connection and logging `Thu Oct 12 22:28:42 2017 -> WARNING: INSTREAM: Size limit reached, (requested: 1024, max: 0)`. The file had a size of 29M.

As a workaround, I've edited /etc/clamav/clamd.conf with new attrs:
```
MaxScanSize 1000M
MaxFileSize 1000M
StreamMaxLength 1000M
```

This has been already said but I'll repeat it to make it clear: in AM 1.6 the user wouldn't have seen the error but the file wasn't really being scanned at all. In AM 1.7 this issue is being exposed by the fact that we replaced clamdscan with a Python library that talks directly to clamd.

**Comment by jhsimpson** [comment]
@sevein I agree with your suggestion:

>When size < 1G: file is streamed/referenced to clamd.
>When size >= 1G: file is scanned using clamscan.

@lwo I also agree that scanning a large file can fail if it uses up all available memory.  The problem with returning with a Pass is that Archivematica then creates a PREMIS event that indicates that virus scanning succeeded, when in fact it did not.  

My suggestion for the 1.7 release is to implement what @sevein  has suggested.  For the 1.8 release maybe we can look at adding a new configuration option, to Skip large files, instead of Pass.  That way we can make sure there is no PREMIS event recorded.  That is a slightly larger change, and only required for very large files.

**Comment by sevein** [comment]
@helenst is working on this.

**Comment by sromkey** [comment]
@currmie , @ross-spencer might be able to help you QA this.

**Comment by ross-spencer** [comment]
@currmie for sure. Let me have a think how best to approach this and I'll pop a note in Slack,

**Comment by ross-spencer** [comment]
@currmie @kellyannewithane if this is marked as done - do we still need to test further? That might save us the question around setting up a VM for now.

**Comment by VinzenzBauer** [comment]
As i just came across this issue in AM V1.9, i thought about letting you know that this issue is still there:
Dashboard > Transfer > Job Scan for viruses (Details):
> archivematicaclamscan_v0.0: INFO      2019-03-15 09:59:16,483  archivematica.mcp.client.clamscan.scan_file:341  Using scanner ClamAV (clamd) (ClamAV 0.100.2 - 25389/Fri Mar 15 07:52:25 2019)
archivematicaclamscan_v0.0: INFO      2019-03-15 09:59:16,483  archivematica.mcp.client.clamscan.pass_by_stream:176  File contents being streamed to Clamdscan.
archivematicaclamscan_v0.0: ERROR     2019-03-15 09:59:16,733  archivematica.mcp.client.clamscan.clamd_exception_handler:151  Virus scanning failed: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematica_clamscan.py", line 118, in scan
    result = getattr(self, method_name)(path)
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematica_clamscan.py", line 177, in pass_by_stream
    return self.client.instream(open(path))
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/clamd/__init__.py", line 190, in instream
    self.clamd_socket.send(size + chunk)
error: [Errno 104] Connection reset by peer
archivematicaclamscan_v0.0: INFO      2019-03-15 09:59:16,734  archivematica.mcp.client.clamscan.scan_file:354  File /var/archivematica/sharedDirectory/currentlyProcessing/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000019.tif scanned!

du -h /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/*

> 33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000001.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000002.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000003.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000004.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000005.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000006.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000007.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000008.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000009.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000010.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000011.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000012.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000013.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000014.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000015.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000016.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000017.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000018.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000019.tif
33M     /var/archivematica/sharedDirectory/failed/116886_1496039057-ecdcb3ea-92e7-490a-afbc-a096126f86af/objects/data/images/scans_tif/00000020.tif
--
I saw that there is a default size-limit of 30 mb and these are 33 mb. Is it advisable to change those defaults?

**Comment by ross-spencer** [comment]
Hi @VinzenzBauer - there's a little information about these settings here: https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/transfer/scan-for-viruses/#exploring-clamav-settings 

Can I ask though what are the settings for each of:
```
MaxScanSize 
MaxFileSize 
StreamMaxLength 
```

And does this issue result in the microservice failing?

**Comment by VinzenzBauer** [comment]
The numbers on that were around 25 mb and the service failed and the package was automatically moved to failed. With the changes however documented here: https://www.archivematica.org/en/docs/archivematica-1.9/admin-manual/installation-setup/customization/antivirus-admin/#antivirus-admin 
it currently works for the tiff tested. But i wonder what happens when we try to ingest historical movie-data with sizes around 4gb which will happen really soon.

**Comment by ross-spencer** [comment]
Hi @VinzenzBauer I believe this setting is the one that needs to be higher than the amount of data that you intend to send `StreamMaxLength`. You'll note too from the docs that there is a limitation on scanning higher than 2GB in ClamAV itself. We provided a little information in the release notes about our expectation that viruses would normally be attached to smaller payloads (e.g. to be sent with emails/websites): https://wiki.archivematica.org/Archivematica_1.7_and_Storage_Service_0.11_release_notes#Anti-virus_changes 

If setting `StreamMaxLength` works for you then we might want to open a ticket to improve the documentation about handling large files and virus scannning. If it doesn't then we should open a ticket to understand how to deal with this situation more gracefully. 

One of the discussions we have been having internally recently is around improving automated testing around microservices. I'll highlight this ticket to the folks looking at this as an example where being able to automatically test the result of different permutations of setting could be a good example test. We could then possibly provide more precise guidance around what you are seeing here cc. @joel-simpson and @sromkey

**Comment by Daniel-Nashed** [comment]
@ross-spencer I am working on a new project integrating clamd into one of my free applications.
I am using IDSESSION with INSTREAM just to prevent opening a new connection for every request (no parallel processing -- I am waiting for very scan to complete in a single thread).

I had some abnormal terminations of clamd so I added reconnect functionality to my application.
It will try to close the socked and opens a new connection.
And I am now testing with killing the clamd process and starting it again to see if my reconnect logic works.

For the first requests after reconnect (new session) I am always getting rejections for a file size around 2 GB (see log results) -- even my requested size is far below that size. 
What I also noticed is that the status returned is an empty string instead of a status for a too large attachment.

A size around 2 GB is pretty close to a 32bit signed integer.  This might not be a coincident.

 I don't understand why, because it is a new process I am connecting to. 
After a couple of reconnects, scanning works again. This is really weird, because it is a new process.
Maybe something is wrong in the way I do the reconnect. I do exactly the same as my very first connect.  I can reproduce it on Windows and Linux.

-- Daniel

Log extract: 
....
Self checking every 600 seconds.
Listening daemon: PID: 22940
MaxQueue set to: 100
WARNING: INSTREAM: Size limit reached, (requested: 2051624531, max: 104802120)
WARNING: INSTREAM: Size limit reached, (requested: 2051624531, max: 104854167)
WARNING: INSTREAM: Size limit reached, (requested: 2051624531, max: 104853320)...

Current test cases:

- start the application and let it scan
- kill the clamd process
- start a new clamd process
- let my application re-connect
- see errors in the debug log about a 2 GB file size
- application get's empty reply and session is closed.
