### ISSUE TITLE
Problem: migration fpr.0015_pronom_92 is invalid

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#792]
The "slug" field in fpr_format table is a varchar(50), and there are slugs with more than 50 chars in this migration.

In centos, mysql drops the characters that exceed the field size silently, but in ubuntu xenial the migration fails to aply.

**Comment by sevein** [comment]
@jrwdunham what do you think we should do here? @scollazo mentioned that the slug causing the issue is `the-neuroimaging-informatics-technology-initiative-2` (52 characters). If we changed the size of the field we're probably going to need to edit the `0015_pronom_92.py` migration so this is done before we load the pronom 92 fixture! Does that sound ok to you?

I could also edit the fixture and remove that `-2` suffix but I know that won't if the user edits the same record because slugfield will try to set the same slug again! That slugfield extension we're using is not great and we should look into that in the future.

This is definitely a blocker for the release!

**Comment by sevein** [comment]
@scollazo #814 fixes the problem.

**Comment by sromkey** [comment]
@scollazo could you please QA this? Thanks.
