### ISSUE TITLE
ElasticSearch timeout when indexing a many-files AIP

### ISSUE THREAD

**Issue by lwo** [artefactual/archivematica#831]
In: qa/1x 
We encounter an issue which looks just like it is solved with #556

When de AIP is indexed, we notice that our settings are ignored and the timeout setting remains set at the default 10.0 at:
qa/1.x/src/archivematicaCommon/lib/elasticSearchFunctions.py#L111

Our settings are in:
/etc/init/archivematica-mcp-client.conf
env ELASTICSEARCH_TIMEOUT=100

And to be sure even in the external file (which we think redundant) :
[MCPClient]
elasticsearch_timeout = 100

Is this a bug or a wrong setting somehow?

**Comment by jhsimpson** [comment]
I believe this issue can be resolved by moving the variable setting to `/etc/archivematica/MCPClient/clientconfig.conf`.

The documentation for how to do this was incorrect and is being fixed in #840 and #845 
You can see details here https://github.com/artefactual/archivematica/blob/dev/docs-envs/src/MCPClient/install/README.md


Try changing the line at
https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/install/clientConfig.conf#L13
so it says 
`elasticsearchTimeout = 100`

**Comment by lwo** [comment]
I am happy to say that setting `elasticsearchTimeout = 100` produces the desired result.
