### ISSUE TITLE
Question: Output from successful clamscan in stderr?

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#841]
Ran a small transfer through on am17xqa - successfully!  Issues:  appears that clamscan is checking all files in the transfer including the mets, processing mcp and fileuuidserror.log. 

stderr for the two items transferred - landing zone.jpg and marbles.tga - shows that the files were scanned and result = passed.  This should be in stdout instead?

stderr for log and mets files show that the file was scanned but not passed (which makes some sense yet this isn't an error)

**Comment by ross-spencer** [comment]
@kellyannewithane the generation of a file scan for these files is controlled by this line of code: https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/lib/clientScripts/archivematicaClamscan.py#L197 

If we haven't a UUID for a file a PREMIS event isn't created which is the line your referencing that says `PASSED` or otherwise. At this point in the scan these files haven't been assigned UUIDs (they weren't associated with the transfer at that point in the process) which seems to be one of the ways we control the generation of PREMIS events for just the transferred files, not what we wrap around them in the AIP. Which makes sense. 

Regarding `stderr` and `stdout` then we chatted, but documentation for our users finding this issue: 

Output to `stderr` for this purpose, in this case, 'successful' results is standard. The `err` part is a bit of a misnomer. We tend to use it in code for 'any output that isn't what the user will want to use in another application' so it often gets used for logging/diagnosis. All of the Archivematica logging goes to `stderr` and instead we see them marked up using codes like `info` `warning` `error` which the sysadmin will often be monitoring for what they're interested in - mostly `warning` and `error` so that they can clean up or fix workflows.

The virus test passing is nice to know, but not critical. This is the same for a fail in some regards depending on what the user wants. We use a combination of the application return code `0` for pass and `1` for fail, or `2` for some other error to indicate one result or another. The user interface and PREMIS events act as a quasi-`stdout` for getting more information about that for which to act upon.

I think these are good questions. If you think there is any way we can document them better then let me know and we can open up a discussion with the crew. I'll await your say-so before closing this issue out.

**Comment by kellyannewithane** [comment]
@ross-spencer Thx for the explanation.  I think we can try to explain better in the user docs and perhaps spend some time on this in training events like at archivematica camps.
