### ISSUE TITLE
Problem: Dublin Core metadata added during Transfer does not show up in the ingest tab template, nor METS

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#842]
Using a 1.7.0-rc2 server, I created a transfer, and used the metadata entry form to add some dublin core metadata during Transfer.  I can see the metadata in the transfer tab, it does not show up in the metadata entry template in the ingest tab (I'm not sure if it is supposed to or not).  

More importantly, the metadata entered in the gui does not appear in the METS file.  There is no dmdSec with the dublin core that was entered during transfer.

**Comment by sromkey** [comment]
This may be related to: https://projects.artefactual.com/issues/8680

**Comment by ross-spencer** [comment]
Tested in `1.10.x` with the following process:

1. Added metadata via the browser at Assign UUIDs to Directories.
2. Waited for Add metadata reminder to appear. 
3. Viewed the MD for 1. in the ingest workflow. It was there.
4. Downloaded the METS once stored, the metadata was there too. 

I'm not sure on the specific commit/issue this was resolved against, but closing as this is fixed in recent versions of Archivematica.
