### ISSUE TITLE
Problem: Appraisal tab file preview doesn't show file

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#884]
When you try to preview a file in Appraisal Tab > Analysis > Preview File, instead of showing the file it just immediately gets downloaded and the file never appears in the preview pane. Tested on augustus and am17x.qa.

**Comment by sromkey** [comment]
@sallain what file format were you trying to preview? Did it happen with all files in the transfer or just this one?

**Comment by sallain** [comment]
@sromkey Happened to all files in the transfer, including Landing_zone.jpg which has previewed fine in the past.

**Comment by ross-spencer** [comment]
Duplicated here: https://github.com/artefactual/archivematica/issues/951

**Comment by ross-spencer** [comment]
In AM 1.6, a request is generated, and that seems to be missing in AM 1.7. There are two packets. The first is a redirect because the URL is not configured correctly, the second, to display the image in the preview pane is:
```
GET /filesystem/eff1a88d-ce1f-44fc-980e-52e6da532e09/download/ HTTP/1.1
Host: sandbox.archivematica.org
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://sandbox.archivematica.org/appraisal/
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: _ga=GA1.2.43492982.1510262923; _gid=GA1.2.1126886303.1520733282; csrftoken=pjJ7BDf9cZBeNRDF15uprV6gCoplm23M; sessionid=w1nb99z74us4n4fsrf59olw9i4udwfta
```
```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 11 Mar 2018 07:15:49 GMT
Content-Type: image/jpeg
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Cookie
```

**Comment by ross-spencer** [comment]
Update:

We're arriving here: [stream_file_from_storage_service()](https://github.com/artefactual/archivematica/blob/ef35d8f821593d28e4dad5e55fa3f357f041c047/src/dashboard/src/components/helpers.py#L309) And the content disposition for files such as jpeg is being set to `attachment; filename="DRy0VU5UMAAtFOT.jpg"`

This disposition type is for downloading a file. The filename appendix exists to repatriate the original name with any name it may be on the server, in our case, the file uuid.

If we force this `content-disposition` to be `inline` we see the preview pane works as anticipated. 

![image](https://user-images.githubusercontent.com/1880412/37251525-a191d346-2576-11e8-8dfa-3696c3d319c4.png)

Now, to figure out why the disposition is being set ti attachment!

**Comment by ross-spencer** [comment]
The stream from storage service function simply sets the content-disposition as it is returned from the server:
```
def stream_file_from_storage_service(url, error_message='Remote URL returned {}'):
    stream = requests.get(url, stream=True, 
                               timeout=django_settings.STORAGE_SERVICE_CLIENT_TIMEOUT)
    if stream.status_code == 200:
        content_type = stream.headers.get('content-type', 'text/plain')
        content_disposition = stream.headers.get('content-disposition')
        response = StreamingHttpResponse(stream, content_type=content_type)
        if content_disposition:
            response['Content-Disposition'] = content_disposition
```
So it doesn't seem like we're doing anything to force these headers particularly. In fact, it seems likely that the preview of these files may only have worked on the basis of being known to the browsers in the first place, i.e. to be in control of their display we would likely need to set `inline` ourselves from the outset. 

As I write, I suspect a fix to this issue is to create a new URL for the dashboard to work with, as preview and download is currently mapped to a url of the following form:

`http://127.0.0.1:62080/filesystem/c0dcb5b6-47e3-427e-9b45-3c23a8f5b56f/download`

We can create another verb here, `preview` and this can be routed through the same functions, but with an additional parameter, `preview=False` so we can set this ourselves at the appropriate point in the code.

We can add it here: https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/dashboard/src/components/filesystem_ajax/urls.py#L25

While this isn't an API by name, the URI patterns are available to the public so we can discuss this in the team as required. 

When I get an opportunity I will take a look as to the impact of this in the `.js` files associated with the preview and file list widgets on the appraisal tab.

**Comment by sallain** [comment]
Now works as expected on all test servers.
