### ISSUE TITLE
MCP config drop-down orders need review

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#891]
Several of the drop-down options appear in illogical or inconsistent order. For example:

```
Select compression level:

#. None
#. 5 - normal compression mode
#. 7 - maximum compression
#. 9 - ultra compression
#. 3 - fast compression mode
#. 1 - fastest mode
```

Also, there are 3 different file identification drop-downs (transfer, ingest, submission docs/metadata) and the order of choices in each of those is different.

Reviewing the order of options (as well as, perhaps, the wording, if possible) and updating them for consistency would be helpful for understanding the processing configuration options.

**Comment by ross-spencer** [comment]
Hi @sallain we managed to fix the order of the compression methods (7z, gzip) etc. in https://github.com/wellcometrust/archivematica/commit/7fdcb35f26b2cc39a244cecb0390a19e7bf30369. If you are interested, I believe they should largely be `workflow.json` changes. So if you look at this section of code [here](https://github.com/wellcometrust/archivematica/blob/7fdcb35f26b2cc39a244cecb0390a19e7bf30369/src/MCPServer/lib/assets/workflow.json#L896-L972) the order is defined by the order that the different JSON objects appear in the square brackets. 

Taking a smaller segment:

```json
        "01c651cb-c174-4ba4-b985-1d87a44d6754": {
            "config": {
                "@manager": "linkTaskManagerReplacementDicFromChoice",
                "@model": "MicroServiceChoiceReplacementDic",
                "replacements": [
                    {
                        "description": {
                            "en": "5 - normal compression mode",
                            "es": "5 - modo de compresión normal",
                            "fr": "5 - mode de compression normal",
                            "ja": "5 - 通常の圧縮モード",
                            "pt_BR": "5 - modo de compressão normal",
                            "sv": "5 - normal komprimeringsläge"
                        },
                        "id": "414da421-b83f-4648-895f-a34840e3c3f5",
                        "items": {
                            "AIPCompressionLevel": "5"
                        }
                    },
                    {
                        "description": {
                            "en": "7 - maximum compression",
                            "es": "7 - máxima compresión",
                            "fr": "7 - compression maximum",
                            "ja": "7 - 最大圧縮",
                            "pt_BR": "7 - compressão máxima",
                            "sv": "7 - maximal komprimering"
                        },
                        "id": "4e31f579-68bd-4be1-a10e-ec5411897121",
                        "items": {
                            "AIPCompressionLevel": "7"
                        }
                    }
                ]
            },
```
To reorder that in the GUI so it becomes, `7` then `5`, you take this entire section:
```json
                    {
                        "description": {
                            "en": "7 - maximum compression",
                            "es": "7 - máxima compresión",
                            "fr": "7 - compression maximum",
                            "ja": "7 - 最大圧縮",
                            "pt_BR": "7 - compressão máxima",
                            "sv": "7 - maximal komprimering"
                        },
                        "id": "4e31f579-68bd-4be1-a10e-ec5411897121",
                        "items": {
                            "AIPCompressionLevel": "7"
                        }
                    },
```
And place it above the first section, so:
```json
        "01c651cb-c174-4ba4-b985-1d87a44d6754": {
            "config": {
                "@manager": "linkTaskManagerReplacementDicFromChoice",
                "@model": "MicroServiceChoiceReplacementDic",
                "replacements": [
                    {
                        "description": {
                            "en": "7 - maximum compression",
                            "es": "7 - máxima compresión",
                            "fr": "7 - compression maximum",
                            "ja": "7 - 最大圧縮",
                            "pt_BR": "7 - compressão máxima",
                            "sv": "7 - maximal komprimering"
                        },
                        "id": "4e31f579-68bd-4be1-a10e-ec5411897121",
                        "items": {
                            "AIPCompressionLevel": "7"
                        }
                    },
                    {
                        "description": {
                            "en": "5 - normal compression mode",
                            "es": "5 - modo de compresión normal",
                            "fr": "5 - mode de compression normal",
                            "ja": "5 - 通常の圧縮モード",
                            "pt_BR": "5 - modo de compressão normal",
                            "sv": "5 - normal komprimeringsläge"
                        },
                        "id": "414da421-b83f-4648-895f-a34840e3c3f5",
                        "items": {
                            "AIPCompressionLevel": "5"
                        }
                    }
                ]
            },
```
The technical reason behind the order presentation is because the `[ ]` brackets indicate an array data structure and when it is read by the machine it is also an instruction to preserve order. 

I'll mark this change as a good first issue too, but it might be one you might want to take a look at as well. Just look for the processing config options in the `workflow.json` file, and if they sit in an array, then consider how they can be swapped around to be a little more intuitive. 

The important thing is that the JSON still validates. I recommend this tool online: https://jsonformatter.curiousconcept.com/ 

And to try it locally, if you are working on a development branch and download it, you just need to restart the Archivematica services for the change to be picked up. If Archivematica doesn't come back up, then the `mcp-server` logs will likely tell you the problem. 

Otherwise I've marked this one for triage for `1.11`. It looks like a nice simple one now to tick-off depending on what other order changes are identified.

**Comment by sallain** [comment]
@ross-spencer Awesome! Thanks for the instructions. This is definitely something I could do (given the time, of course :joy:)

**Comment by sallain** [comment]
I've realized that at least one dropdown menu was not changed - the approve reingest dropdown - because it doesn't appear in the processing configuration (I was using the processing config screen layout as guidance.) I'll make another little PR to get this fixed, since it'll only take a few minutes and otherwise it may get lost.

**Comment by sallain** [comment]
I've fixed the issue in the comment above; this now looks good. Tested on qa/1.x on Bionic.

**Comment by sallain** [comment]
NTS: check documentation throughout for screenshots to update.
