### ISSUE TITLE
Problem: empty transfer directories are showing up in the normative logical structmap

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#983]
The "normative directory structure" logical structMap in the AIP METS is supposed to document user-supplied empty directories so that these can be reconstructed, if desired, after Archivematica deletes them (as required by the BagIt spec). However, the current code (archivematicaCreateMETS2.py) is also documenting empty directories that are not user-supplied, namely those in objects/metadata/transfers/ such as objects/metadata/transfers/my_transfer_dir/. 

To re-create, configure AM to document empty directories and to assign UUIDs to directories and create an AIP from archivematica-sampledata/SampleTransfers/Images/pictures/. Then observe that the AIP METS' logical structMap will be documenting objects/metadata/transfers/pictures-<UUID>/.

**Comment by jrwdunham** [comment]
To QA this issue, do the following:

1. Configure AM to document empty directories and to assign UUIDs to directories.
2. Create an AIP from archivematica-sampledata/SampleTransfers/Images/pictures/.
3. Inspect the AIP METS and confirm the following
    - The logical structMap should NOT be documenting an empty directory that was the original location of the transfer, e.g., something like `objects/metadata/transfers/pictures-<UUID>/` should not be in the logical ("Normative Directory Structure") structMap.
    - There should be a dmdSec for the AIP as a whole (at the top of the METS) but there should NOT be a dmdSec for the empty transfer directory, e.g., the `objects/metadata/transfers/pictures-<UUID>/` directory.

**Comment by sallain** [comment]
For the logical structmap issue: I'm only seeing three directories in the logical structmap: `objects`, `objects/metadata`, and `objects/metadata/transfers`, which is what I would expect (all are present in the AIP). So this issue looks resolved.

For the dmdSec issue: there's only one dmdSec in the METS, and it's the one for the AIP as a whole. No other dmdSecs are present, which is the expected result. This issue is resolved as well.
