### ISSUE TITLE
Problem: Default processing config is automated on install

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#993]
On new installations of Archivematica the processing config is now set to a default to automate everything. While this might be desirable from an automated testing point of view it catches users off guard. The previous default processing config (from 1.6.1) would be more appropriate from a user's point of view.

**Comment by sallain** [comment]
@sromkey How does this look for a default setup? I tried to think about how I would want to talk through each of the decision points during a demo. The only thing I think is really contentious (WRT users using these configs out-of-the-box) is setting the compression level to _1 - fastest mode_ rather than _5 - normal compression mode_, since I've prioritized faster compression time over package size. 

![processing-config](https://user-images.githubusercontent.com/4612276/37626444-4c1de5f4-2b8d-11e8-8758-37d62cf51f76.jpg)

**Comment by sromkey** [comment]
It seems like a lot more blank decisions than we had in previous releases but I'm ok with that. I think the only other thing I would set is File identification in ingest use "Use existing data" since that works in the vast majority of use cases.

We should maybe make a note in the release notes that we've changed the defaults so people will (hopefully) not be caught off guard.

**Comment by sevein** [comment]
@scollazo can you please download the processing configs from augustus and share it here please? Or add my ssh key to the hosts, and if you do so please make it so it's permanent if you can because I keep having the same access issue.

**Comment by sevein** [comment]
https://gist.github.com/sevein/11a8d000b765269864a092c735a43db3

**Comment by sevein** [comment]
Once #1005 is merged, for QA make sure that the configurations in the shared directory are deleted then restart MCPServer and they should be populated again (CC @scollazo @mamedin, this will have to be done in the QA server).

**Comment by sallain** [comment]
Checked this over on the test servers and it looks good!
